# Dive Risk Analysis Configuration

paths:
  data_dir: "data"
  output_dir: "outputs"
  input_csv: "diving_synthetic_profiles.csv"
  
output_files:
  html_report: "comprehensive_diving_analysis.html"
  main_plots: "comprehensive_analysis_plots.png"
  partial_plots: "partial_dependence_plots.png"
  residual_plots: "residual_plots.png"
  model_comparison: "model_comparison.csv"
  odds_ratios: "odds_ratios.csv"
  marginal_effects: "marginal_effects.csv"
  performance: "model_performance.csv"
  predictions: "predictions.csv"
  vif_scores: "vif_scores.csv"

feature_engineering:
  create_squared_depth: true
  create_nitrox_binary: true
  create_depth_time_interaction: true

model_formulas:
  baseline: "Incident ~ MaxDepth_m + BottomTime_min + AscentRate_m_per_min + SafetyStop + NDL_Violation"
  full: "Incident ~ MaxDepth_m + I(MaxDepth_m**2) + BottomTime_min + AscentRate_m_per_min + SafetyStop + NDL_Violation + MaxDepth_m:BottomTime_min + Nitrox"

analysis:
  classification_threshold: 0.5
  hosmer_lemeshow_groups: 10
  vif_threshold: 10.0
  residual_outlier_threshold: 3.0
  
cross_validation:
  n_splits: 5
  shuffle: true
  random_state: 42
  scoring: "roc_auc"

plotting:
  style: "whitegrid"
  figure_size: [14, 10]
  dpi: 300
  depths_for_interaction: [15, 25, 35, 45]

scenarios:
  - name: "Safe Recreational Dive"
    MaxDepth_m: 18
    BottomTime_min: 40
    AscentRate_m_per_min: 10
    SafetyStop: 1
    NDL_Violation: 0
    Nitrox: 0
    
  - name: "Deep Dive with Safety Stop"
    MaxDepth_m: 35
    BottomTime_min: 25
    AscentRate_m_per_min: 10
    SafetyStop: 1
    NDL_Violation: 0
    Nitrox: 1
    
  - name: "Risky: Deep + Long + No Safety Stop"
    MaxDepth_m: 40
    BottomTime_min: 35
    AscentRate_m_per_min: 12
    SafetyStop: 0
    NDL_Violation: 0
    Nitrox: 0
    
  - name: "Very Risky: Fast Ascent + NDL Violation"
    MaxDepth_m: 35
    BottomTime_min: 30
    AscentRate_m_per_min: 20
    SafetyStop: 0
    NDL_Violation: 1
    Nitrox: 0